[package]
name = "trace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.18.0"
crossterm = "0.23"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand = "0.8"
chrono = "0.4"